site: cm0
url: https://cm0.dev
title: Clarence M.
tagline: IT/Programming Blog
description: >-
  This blog is a place to share my knowledge and experience within the world of IT.

author:
  name: Clarence M.
  url: https://cm0.dev

googlewebfonts: Roboto+Mono:wght@400;500;700
permalink: pretty
paginate: 10
baseurl: ""
markdown: kramdown
highlighter: rouge

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"